### ISSUE TITLE
pip install: metadata-generation-failed

### ISSUE THREAD

**Issue by tyralla** [sphinx-contrib/fulltoc#23]
Thanks for providing *fulltoc*!

Travis-CI cannot install *fulltoc* for my workflow for some days now.  Unfortunately, I cannot reproduce the problem on my computer (Windows, Python 3.9), so it is hard to fix this.  Any advice?

```
Python 3.7.1
$ pip --version
pip 22.0.4 from /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pip (python 3.7)
install.1
2.12s$ pip install --upgrade pip virtualenv
5.46s$ pip install -r requirements.txt
Requirement already satisfied: attrs in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (21.4.0)
Collecting black
  Downloading black-22.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
Collecting bokeh
  Downloading bokeh-2.4.2-py3-none-any.whl (18.5 MB)
Collecting build
  Downloading build-0.7.0-py3-none-any.whl (16 kB)
Collecting click
  Downloading click-8.1.1-py3-none-any.whl (96 kB)
Collecting coverage
  Downloading coverage-6.3.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (207 kB)
Collecting Cython
  Downloading Cython-0.29.28-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
Collecting docutils
  Downloading docutils-0.18.1-py2.py3-none-any.whl (570 kB)
Collecting lastversion
  Downloading lastversion-2.2.2-py3-none-any.whl (55 kB)
Collecting matplotlib
  Downloading matplotlib-3.5.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
Collecting netcdf4
  Downloading netCDF4-1.5.8-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
Collecting networkx
  Downloading networkx-2.6.3-py3-none-any.whl (1.9 MB)
Collecting nox
  Downloading nox-2022.1.7-py3-none-any.whl (51 kB)
Requirement already satisfied: numpy in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (1.16.4)
Requirement already satisfied: packaging in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (19.0)
Collecting pandas
  Downloading pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
Collecting plotly
  Downloading plotly-5.6.0-py2.py3-none-any.whl (27.7 MB)
Collecting pynsist
  Downloading pynsist-2.8-py3-none-any.whl (2.8 MB)
Requirement already satisfied: setuptools in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from -r requirements.txt (line 19)) (60.10.0)
Collecting typing_extensions
  Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting scipy
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
Collecting sphinx
  Downloading Sphinx-4.5.0-py3-none-any.whl (3.1 MB)
Collecting sphinxcontrib-bibtex
  Downloading sphinxcontrib_bibtex-2.4.1-py3-none-any.whl (38 kB)
Collecting sphinxcontrib-fulltoc
  Downloading sphinxcontrib-fulltoc-1.2.0.tar.gz (13 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
          from setuptools.dist import Distribution
        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
          from ._importlib import metadata
        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 28, in <module>
          disable_importlib_metadata_finder(metadata)
        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 12, in disable_importlib_metadata_finder
          import importlib_metadata
        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 471, in <module>
          __version__ = version(__name__)
        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 438, in version
          return distribution(package).version
        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 411, in distribution
          return Distribution.from_name(package)
        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 179, in from_name
          dists = resolver(name)
        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 886, in find_distributions
          found = self._search_paths(context.name, context.path)
      AttributeError: 'str' object has no attribute 'name'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
The command "pip install -r requirements.txt" failed and exited with 1 during .
```

**Comment by tyralla** [comment]
I switched to Python 3.9 (and Focal) on Travis-CI, which solved the problem.
